import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'dagger.hilt.android.plugin'
}

android {
    namespace 'com.apodacatech.inbite'
    compileSdk ProjectConfig.compileSdk

    defaultConfig {
        applicationId "com.apodacatech.inbite"
        minSdk ProjectConfig.minSdk
        targetSdk ProjectConfig.targetSdk
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }
    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion ProjectConfig.extensionVersion
    }
    packaging {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {

    implementation libs.hilt.android
    kapt libs.hilt.compiler
    implementation libs.hilt.navigation.compose

    //Timber
    implementation libs.timber

    implementation libs.arrow.core
    implementation libs.arrow.fx.coroutines

    implementation libs.core.ktx
    implementation libs.lifecycle.runtime
    implementation libs.activity.compose
    implementation platform(libs.compose.bom)
    implementation libs.compose.ui
    implementation libs.compose.ui.graphics
    implementation libs.compose.tooling.preview
    implementation libs.material3.compose
    implementation libs.androidx.core.splashscreen

    testImplementation libs.junit
    androidTestImplementation libs.junit.ext
    androidTestImplementation libs.espresso.core
    androidTestImplementation platform(libs.compose.bom)
    androidTestImplementation libs.compose.ui.test
    debugImplementation libs.compose.ui.tooling
    debugImplementation libs.compose.ui.test.manifest

    implementation(project(":core:ui"))
    implementation(project(":core:model"))
    implementation(project(":core:data"))
    implementation(project(":core:network")) // TODO : Remove this line, and organize modules properly for network models and data models
}
tasks.withType(KotlinCompile).all {
    kotlinOptions {
        languageVersion = "1.9"
    }
}